version: '3.8'

services:
  diabetes-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diabetes-prediction-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=False
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 